# Generated by Django 5.2 on 2025-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
