# Generated by Django 5.2 on 2025-04-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_api', '0002_alter_palabra_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra',
            name='anwser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
